language: c++

os:
  - osx

compiler:
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install Caskroom/cask/xquartz gdal xerces-c homebrew/x11/fox; fi
script:
  - cd sumo
  - make -f Makefile.cvs
  - export CPPFLAGS="$CPPFLAGS -I/opt/X11/include -I/usr/local/include"
  - export LDFLAGS="-L/opt/X11/lib -stdlib=libc++"
  - ./configure CXX=clang++ CXXFLAGS="-stdlib=libc++ -std=gnu++11" --with-xerces=/usr/local --with-proj-gdal=/usr/local --enable-debug 
  - make -j4
